### ISSUE TITLE
CREDENTIAL: Explicitly describe the extension model.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#252] opened 2015-04-14 04:38 UTC
I don't think the current draft makes the extension points clear. Let's improve that.

**Comment by jonathanKingston** [comment] 2015-04-14 05:57
Relates to/is duplicate of: #251

**Comment by mikewest** [comment] 2015-04-14 08:44
Here, I mean "extension" as in "`Credential` is subclassed by `LocalCredential` now, and could be subclassed by `AmazingNewTypeOfCredential` in the future.", not "extension" as in "browser extension". I think the issues are indeed distinct.

**Comment by jonathanKingston** [comment] 2015-04-14 11:32
I meant the same form of "extension" as in classical inheritance but for different reasons.

I thought this was what you spoke about when you mentioned plugins/extensions could override or extend the functionality of window.navigator.credentials.store.

---

However certainly improving the paragraph at the start of section 3.1 would help here:
https://w3c.github.io/webappsec/specs/credentialmanagement/#interfaces-credential-types

Perhaps also use stronger language like: "All credential types MUST extend from the base interface credential..."

**Closed** 2015-04-19 19:41 UTC
Labels: CREDENTIAL
